# Generated by Django 3.2.3 on 2021-05-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_var_varmean'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='Start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='var',
            name='VarMean',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.varoption', verbose_name='Её значения'),
        ),
    ]
