# Generated by Django 3.2.3 on 2021-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210514_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='MeaningToAttestation',
            field=models.CharField(max_length=255, null=True, verbose_name='Отображение переменной для пользователя'),
        ),
        migrations.AddField(
            model_name='var',
            name='MeaningToUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Отображение переменной для пользователя'),
        ),
        migrations.AddField(
            model_name='var',
            name='QuoteMean',
            field=models.CharField(max_length=20, null=True, verbose_name='Уникальный идентификатор для цитирования'),
        ),
    ]
