# Generated by Django 3.2.3 on 2021-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_varslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='QuoteMean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.varslug', verbose_name='Уникальный идентификатор для цитирования'),
        ),
    ]
