# Generated by Django 3.2.3 on 2021-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_var_quotemean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='MeaningToAttestation',
            field=models.CharField(max_length=255, null=True, verbose_name='Отображение переменной для авторизированного пользователя'),
        ),
    ]
